blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
post_list,
post_detail,
post_create,
post_edit,
post_delete,
recent_posts,
month_archive,
year_archive,
)

urlpatterns = [
    url(r'^$', recent_posts, name='recent_posts'),
    url(r'^post/$', post_list, name="list"),
    url(r'^post/create/$', post_create, name="create"),
    url(r'^post/archive/(?P<year>[0-9]{4})/$', year_archive, name="year_archive"),
    url(r'^post/archive/(?P<year>[0-9]{4})/?P<month>([0-9]{2})/$', month_archive, name="month_archive"),
    url(r'^post/(?P<slug>[\w-]+)/$', post_detail, name="detail"),
    url(r'^post/(?P<slug>[\w-]+)/edit/$', post_edit, name="edit"),
    url(r'^post/(?P<slug>[\w-]+)/delete/$', post_delete, name="delete"),

    ]

tourism_configs/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include ("blog.urls", namespace="post")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import os
from PIL import Image

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.text import slugify


from tourism_configs.settings import BASE_DIR
# Create your models here.

class PostManager (models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager,self).filter(draft=False).filter(published_date__lte=timezone.now())

def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
            null=True,
            blank=True,
            height_field="height_field",
            width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    published_date = models.DateTimeField(blank=True, null=True, default=timezone.now)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    objects = PostManager()

    class Meta:
        ordering = ["-published_date","-updated"]

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        super(Post, self).save()
        if self.image:
            size = (300, 300)
            image_path = str(self.image.path)
            im = Image.open(size)
            im.thumbnail(medium_size)
            original_image_full_path = os.path.join(BASE_DIR, self.image.path)
            os.remove(original_image_full_path)

            im.save(original_image_full_path)
            super(Post, self).save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse("post:detail", kwargs={"slug":self.slug})

    def publish(self):
        self.published_date = timezone.now()
        self.save()



def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, sender=Post)

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "image",
            "content",
            "draft",
            "published_date",
        ]

blog/views.py
from urllib.parse import quote_plus

from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render,get_object_or_404, redirect
from django.utils import timezone

from .models import Post
from .forms import PostForm

# Create your views here.

def recent_posts(request):
    query_list = Post.objects.active()
    total_posts = query_list.count
    recent_articles = Post.objects.active()[:2]

    if request.user.is_staff or request.user.is_superuser:
        recent_articles = Post.objects.all()[:2]
        query_list = Post.objects.all()
        total_posts = query_list.count

    search_query = request.GET.get("q")
    if search_query:
        query_list = query_list.filter(
        Q(title__icontains=search_query) |
        Q(content__icontains=search_query) |
        Q(user__first_name__icontains=search_query) |
        Q(user__last_name__icontains=search_query)
        ).distinct()

        total_posts = query_list.count
        recent_articles = query_list

    context = {
    "page_title": "Recent Articles",
    "recent_articles": recent_articles,
    "all_articles": total_posts
    }

    return render(request,"index.html", context)


def post_list(request):
    query_list = Post.objects.active()
    total_posts = query_list.count
    # year_archive = year_archive2()
    if request.user.is_staff or request.user.is_superuser:
        query_list = Post.objects.all()

    search_query = request.GET.get("q")
    if search_query:
        query_list = query_list.filter(
        Q(title__icontains=search_query) |
        Q(content__icontains=search_query) |
        Q(user__first_name__icontains=search_query) |
        Q(user__last_name__icontains=search_query)
        ).distinct()

    paginator = Paginator(query_list, 5)
    page_request_var = "page"
    page = request.GET.get("page")

    total_posts = paginator.count
    try:
        page_list = paginator.page(page)
    except PageNotAnInteger:
        page_list = paginator.page(1)
    except EmptyPage:
        page_list = paginator.page(paginator.num_pages)

    context = {
    "list": page_list,
    "page_title": "All Articles",
    "page_request_var": page_request_var,
    "all_articles": total_posts
    }
    return render(request,"post_list.html", context)


def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    context= {
        "form": form,
        "page_title": "Create New Post"
    }
    return render(request,"post_create.html", context)

def post_detail(request, slug):
    instance = get_object_or_404(Post, slug= slug)

    share_string = quote_plus(instance.content)


    if instance.draft or instance.published_date > timezone.now():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    context = {
        "title": "instance.title",
        "instance": instance,
        "share_string": share_string,
    }

    return render(request,"post_detail.html", context)


def post_edit(request, slug):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug= slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Post Was Successfully Updated")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "form": form,
        "page_title": "Edit Post"
    }
    return render(request,"post_create.html", context)


def post_delete(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, id= id)
    instance.user = request.user
    instance.delete()
    messages.success(request, "Post Deleted Successfully")
    return redirect("post:list")


def year_archive(request, year):
    query_list = Post.objects.active().filter(published_date__year=year)
    context = {'year': year, 'article_list': query_list}
    return render(request, 'year_archive.html', context)

def month_archive(request, year, month):
    query_list = Post.objects.active().filter(published_date__month=month)
    context = {'month': month, 'article_list': query_list}
    return render(request, 'month.html', context)

blog/templates/base.html
<!DOCTYPE html>
{% load static from staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="//fonts.googleapis.com/css?family=Lobster&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

    <title>{% block title %}Bolu Ola {% endblock title %}</title>
  </head>

  <body>
    <div id="fb-root"></div>
       <script>(function(d, s, id) {
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) return;
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));</script>
  <!-- Fixed navigation bar -->

    <nav class="navbar navbar-default custom-navbar navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand brand" id="corner-name" href="/">Bolu Ola.</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          {% include "search_form.html" %}
          <ul class="nav navbar-nav navbar-right ">
            <li><a class="nav-links" href="/">Home</a></li>
            <li><a class="nav-links" href="{% url 'post:list' %}">All Articles</a></li>
            {% if user.is_authenticated %}
            <li><a class="nav-links" href="{% url 'post:create' %}">Create Post</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <!--/.end of navigation bar -->


    <!-- main section -->

   {% include "message_display.html" %}

      {% block content %}
      {% endblock content %}



  <footer class="footer">
    <p class="text-muted"><small id="copyright">
      © copyright Bolu Ola {% now "Y" %}.
    </small></p>
  </footer>


     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
     <script src="{% static 'js/jquery11.min.js' %}"></script>
     <script src="{% static 'js/bootstrap.min.js' %}"></script>
     <script src="{% static 'js/collapse.js' %}"></script>
     <script src="{% static 'js/blog.js' %}"></script>
    </body>
  </html>

blog/templates/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block content %}

{% include "jumbotron.html" %}
<!-- search_form was included here -->
  <div class="container">
    <div class="row">

    <div class="recent-articles col-sm-12">
      <div class="">
        <h1 id="page_title">{{page_title}}</h1>
      </div>
      {% for item in recent_articles %}
          <div class="recent col-md-6">
              <a id="recent_article_link" href="{{item.get_absolute_url}}">
                {% if item.draft %}
                <h3 style="color:red">Staff Only: Draft</h3>
                {% endif %}
                {% if item.published_date > timezone.now %}
                <h3>Staff Only: Future Post</h3>
                {% endif %}

                <h3>{{item.title}}<small id="date"> {{item.published_date| timesince}} ago</small></h3>

                {% if item.user.get_full_name%}
                <p id="author">Author: {{item.user.get_full_name}}</p>
                <hr>
                {% endif %}
                <blockquote cite="">
                <p>{{item.content| safe | truncatewords:40}}</p>
                </blockquote>
              </a>
            </div>
      {% endfor %}
    </div>

  </div>
</div>
{% endblock %}

blog/templates/jumbotron.html
<div class="jumbotron">
    <h1>Bolu's Tourism Blog</h1>
    <h3>this is just a test to see what's going on</h3>
</div>


<div class="clearfix"></div>

blog/templates/message_display.html
{% if messages %}
  <div class="action_message">
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
  </div>
{% endif %}

blog/templates/post_create.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block head_title %}
  {{page_title}} | {{block.super}}
{% endblock %}

{% block content %}

  <div class="col-sm-6 col-sm-offset-3">
    <h1>{{page_title}}</h1>
    <form class="create" action="" enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{ myform.media }}
      {{form | crispy}}
      <p><input type="submit" class="btn btn-primary" name="" value="Create Post"></p>
    </form>
  </div>

{% endblock content %}

blog/templates/post_detail.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load urlify %}

{% block head_title %}
  {{instance.title}} | {{block.super}}
{% endblock %}

{% block content  %}
  <div class="col-md-7 col-md-offset-1 detail">
  <div class="thumbnail">
    <div class="caption">

    {% if user.is_authenticated %}
    <div class="edit_button pull-right">
      <a class="btn btn-default" href="{% url 'post:edit' slug=instance.slug %}"><span class="glyphicon glyphicon-pencil"></span></a>
      <a class="btn btn-default" href="{% url 'post:delete' slug=instance.slug %}"><span class="glyphicon glyphicon-trash"></span></a>
    </div>
    {% endif %}

      <div class="">
        <h1>{{instance.title}}
          {% if instance.draft %}
          <span style="color:red">This is a Draft</span>
          {% endif %}
          <span><small id="date">{{instance.published_date | timesince}}</small></span>
        </h1>

        {% if instance.user.get_full_name%}
        <p>Author: {{instance.user.get_full_name}}</p>
        {% endif %}
      </div>

      {% if instance.image %}
      <div class="full-image">
        <img src="{{instance.image.url}}" alt="{{instance.image.name}}" class="img-responsive detail-image" />
      </div>
      {% endif %}

      <div class="fb-like" data-href="{{request.build_absolute_uri}}" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
      <hr>
      <!-- <div class="share_links">

      <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">Facebook</a>

      <a href="https://twitter.com/home?status={{instance.content|truncatechars:140|urlify}}%20{{request.build_absolute_uri}}">Twitter</a>

      <a href='https://plus.google.com/share?url={{request.build_absolute_uri}}'>Google+</a>

      <a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{instance.title}}&summary={{instance.content|truncatechars:140|urlify}}&source={{request.build_absolute_uri}}">Linkedin</a>

      <a href="http://www.reddit.com/submit?url={{request.build_absolute_uri}}&title={{instance.content|truncatechars:140|urlify}}">Reddit</a>
    </div> -->

      <p>{{instance.content | safe }}</p>
      <hr>

      <div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-numposts="5"></div>
      <hr>
    </div>
  </div>

  </div>

{% endblock content %}

blog/templates/post_list.html
{% extends "base.html" %}
{% load static from staticfiles %}



{% block head_title %}
  {{page_title}} | {{block.super}}
{% endblock %}

{% block content %}

<div class="container">

  <div class="row">
    <div class="col-md-8">
      <h1 id="page_title">{{page_title}}</h1>

      {% for item in list %}
        <div class="thumbnail">
          <a id="article_link" href="{{item.get_absolute_url}}">
            {% if item.image %}
            <img src="{{item.image.url}}" alt="item.image.name" class="img-responsive list-image" />
            {% endif %}
            <div class="caption">
            {% if item.draft %}
            <h3 style="color:red">Staff Only: Draft</h3>
            {% endif %}

            {% if item.published_date > timezone.now %}
            <h3>Staff Only: Future Post</h3>
            {% endif %}

            <h3>{{item.title}}</h3>
            <p><small id="date">{{item.published_date| timesince}} ago</small></p>

            {% if item.user.get_full_name%}
            <p>Author: {{item.user.get_full_name}}</p>
            {% endif %}

            <p>{{item.content| safe | truncatewords:40}}</p>
          </a>
          </div>
        </div>
        <hr>
      {% endfor %}
    </div>


  <div class="col-md-8 col-md-offset-2">

  <div class="pagination">
      <span class="step-links">
          {% if list.has_previous %}
              <!--<a href="?page={{ list.previous_page_number }}">previous</a>-->
              <a href="?{{page_request_var}}={{ list.previous_page_number }}
              {% if request.GET.q %}
              &q={{request.GET.q}}
              {% endif %}"
              class="btn btn-success" role="button">
              Previous Page</a>
          {% endif %}

          <span class="current-items">
              Page {{ list.number }} of {{ list.paginator.num_pages }} Showing
              item {{list.start_index}} to {{list.end_index}} of {{all_articles}}
          </span>
          <span>
          {% if list.has_next %}
            <!--<a href="?page={{ list.next_page_number }}">next</a>-->
            <a href="?{{page_request_var}}={{ list.next_page_number }}
            {% if request.GET.q %}
            &q={{request.GET.q}}
            {% endif %}"
            class="btn btn-success" role="button">
            Next Page</a>
          {% endif %}
        </span>

    </div>
  </div>
  {% include 'year_archive.html' %}
  </div>
</div>
{% endblock content %}

blog/templates/search_form.html
  <!-- <div class="container"> -->
  <div class=" col-sm-6 search_form">
    <form id="search" action="" method="GET" class="" role="search">
      <div class="input-group">
        <input class="form-control" type="text" name="q" placeholder="Search Articles" value="{{request.GET.q}}"/>
        <span class="input-group-btn">
          <input type="Submit" value="Search" class="btn btn-success"/>
        </span>
      </div>
    </form>
    {% if request.GET.q %}
    <span class="current-items">
      {{all_articles}} articles matching search
    </span>
    {% endif %}

  </div>
  <!-- </div> -->

blog/templates/year_archive.html
<div class="col-md-4">
  <ul>
    {% for article in article_list %}
      <li>{{article}}</li>
    {% endfor %}
  </ul>

</div>